name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: 
        fetch-dept: 0


    - name: Docker Login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.TOKEN_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD


    - name: Build Docker Image
      run: |
        docker build -t fredost/grapql:0.0.2 .
        docker build -t fredost/grapql:latest .

    - name: Push Docker Image
      run: |
        docker push fredost/grapql:0.0.2
        docker push fredost/grapql:latest
      
            # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
